### ISSUE TITLE
keyerror:"SRL3".phoenix data reading failed in resistics 0.0.6. Procedure

### ISSUE THREAD

**Issue by mshe0528** [resistics/resistics#38]
Hi everyone, I am very interested in processing magnetotellus data, and when following the tutorial, I used phoenix data, which includes TBL header files and TS3,TS4,TS5 files.The code is as follows
#-----------------------
from datapaths import phnx_projectPath, phnx_imagePath
from resistics.time.reader_phoenix import TimeReaderPhoenix

# read in spam data
phoenixPath =  r"C:\006pro\phnxproject\timeData\site1\phnx_DZ34"
phoenixReader = TimeReaderPhoenix(phoenixPath)
phoenixReader.printDataFileInfo()
phoenixReader.printInfo()
#----------------------
But there was a keyword error:
Traceback (most recent call last):
  File "C:\Users\209\.conda\envs\for_006\read_phnx.py", line 6, in <module>
    phoenixReader = TimeReaderPhoenix(phoenixPath)
  File "C:\Users\209\.conda\envs\for_006\Lib\site-packages\resistics\time\reader.py", line 182, in __init__
    self.readHeader()
  File "C:\Users\209\.conda\envs\for_006\Lib\site-packages\resistics\time\reader_phoenix.py", line 518, in readHeader
    self.headers, self.chanHeaders = self.headersFromTable(self.tableData)
  File "C:\Users\209\.conda\envs\for_006\Lib\site-packages\resistics\time\reader_phoenix.py", line 735, in headersFromTable
    self.tsSampleFreqs.append(tableData["SRL{}".format(tsNum)])
KeyError: 'SRL3'
I really can not find the reason for the error, I suspect that it is the problem of the data itself, but I do not know how to solve it, please help to answer

**Comment by mshe0528** [comment]
The problem has been solved

**Comment by nss350** [comment]
Closing as the problem has been solved
